name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  install_dependencies:

    runs-on: ubuntu-latest

    steps:
      - name: install necessary dependencies
        working-directory: ./cs4530a3
        run: npm install
      - name: build files
        working-directory: ./cs4530a3
        run: npm run build
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name : run tests
        working-directory: ./cs4530a3
        run: npm run test
